### ISSUE TITLE
Termos e condições

### ISSUE THREAD

**Issue by ommartins** [ifthenpay/mbway-magento#2]
Caros,
Temos os serviços multibanco e mbway da Ifthenpay e instalamos ambas as extensões dos respetivos métodos de pagamento no magento 2. 
No caso do multibanco (e transferências bancárias), a checkbox para se aceitar os termos e condições aparecem nos respetivos blocos. No caso do Mbway já não aparece, o último bloco é o form para se introduzir o telemóvel.

Estamos em fase de arranque para o nosso site de ecommerce e precisavamos da vossa ajuda.

Melhores Cumprimentos,
Oscar Martins

[ifthenpay_termos_condicoes.pdf](https://github.com/ifthenpay/mbway-magento/files/4788512/ifthenpay_termos_condicoes.pdf)

**Comment by LeoNun** [comment]
Boa tarde Sr. Oscar,
de facto a mim também não me aparece a aceitação dos termos no MBWay e no Payshop, nos outros métodos todos aparecem, de facto será melhor enviarmos um email ao suporte da Ifthenpay.

Cumprimentos,
Leonel Nunes

**Comment by ommartins** [comment]
Caro Leonel,

Desculpe mas fiquei agora um pouco baralhado com a sua resposta, pois
pensava que quem mantinha o código no github era a equipa de
desenvolvimento da Ifthenpay.

É suposto seremos nós a colocar a questão à Ifthenpay?

Obrigado e Cumprimentos,
Oscar

A terça, 16/06/2020, 20:00, LeoNun <notifications@github.com> escreveu:

**Comment by LeoNun** [comment]
Boa noite Sr. Óscar,
Sim, é a equipa da Ifthen que mantém os módulos oficiais a funcionar, no entanto já enviei um email a indicar o seu reparo, que de facto está a acontecer também com o modulo do Payshop.

Cumprimentos,
Leonel Nunes

**Comment by ommartins** [comment]
Muito obrigado Leonel,

Fico então a aguardar.

Melhores cumprimentos,
Oscar

A terça, 16/06/2020, 21:50, LeoNun <notifications@github.com> escreveu:

**Comment by ricardosantoscarvalho** [comment]
Boa tarde,

O erro reportado foi corrigido.

Devem reinstalar o módulo e ativar a opção termos e condições no backoffice.

**Comment by LeoNun** [comment]
Boa tarde,
reinstalado e confirmo que este problema foi resolvido.

Obrigado Sr. Ricardo,

Cumprimentos,
Leonel Nunes

**Comment by ommartins** [comment]
Boa tarde,

Já testei e está a funcionar.

Fiquei bastante impressionado e agradado pela rapidez da vossa resposta ao
meu contacto e pela resolução do problema.
Parabéns e Obrigado.

Melhores Cumprimentos,
Oscar Martins
